variables:
  service_name: gp-connect-prescriptions-management-fhir
  short_service_name: gcpmf
  service_base_path: gp-connect/patient-facing/prescriptions-management-fhir/FHIR/R4
  pr_number: ${{ split(variables['Build.SourceBranch'], '/')[2] }}

